name: Coverage Report

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  coverage-report:
    name: Coverage Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.9' 
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Generate coverage report
        run: |
          pip install coverage==4.3
          coverage run --source=./ -m unittest discover -p "coverage_test.py"
          coverage xml
      
      - name: Upload coverage to code climate
        env:
          CODECLIMATE_REPO_TOKEN: ${CodeClimateToken}
        run: |
          pip install codeclimate-test-reporter
          codeclimate-test-reporter